package:
  name: microdrop-launcher
{% if GIT_DESCRIBE_NUMBER > '0' %}
  version: {{ GIT_DESCRIBE_TAG[1:] }}.post{{ GIT_DESCRIBE_NUMBER }}
{% else %}
  version: {{ GIT_DESCRIBE_TAG[1:] }}
{% endif %}

build:
  entry_points:
    - microdrop-profile-manager = microdrop_launcher.bin.profile_launcher:main
    - launch-microdrop = microdrop_launcher.bin.launch:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - python 2.7*
    - appdirs
    - conda-helpers >=0.9
    - futures
    - jinja2
    - microdrop-plugin-manager >=0.20.2
    - paver
    - pip-helpers >=0.6.post3
    - pycairo-gtk2
    - wheeler.pygtkhelpers >=0.14.post7

  run:
    - appdirs
    - conda-helpers >=0.9
    - futures
    - jinja2
    - microdrop-plugin-manager >=0.20.2
    - pip-helpers >=0.6.post3
    - pycairo-gtk2
    - wheeler.pygtkhelpers >=0.14.post7

# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../

about:
  home: http://github.com/wheeler-microfluidics/microdrop-launcher
  license: BSD
